In [1]:
import numpy as np  

In [2]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [3]:
a[0] = 5                  
print(a)  

[5 2 3]


In [4]:
b = np.array([[1,2,3], [4,5,6]])     
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [5]:
a = np.zeros((2, 2))          
print(a)  

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [7]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [9]:
e = np.random.random((2, 2))
print(e)

[[0.41744173 0.12886672]
 [0.82035767 0.86591529]]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
b = a[:2, 1:3]

In [12]:
print(a[0, 1]) 
b[0, 0] = 77
print(a[0, 1])

2
77


In [13]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [14]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])


In [16]:
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) 
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [17]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) 

[ 1  6  7 11]


In [19]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [20]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [21]:
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [22]:
x = np.array([1, 2])
print(x.dtype)

int64


In [23]:
x = np.array([1.0, 2.0]) 
print(x.dtype)

float64


In [24]:
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64


In [25]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [26]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [27]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [28]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [29]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [31]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

In [32]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [33]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [34]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [35]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [36]:
v = np.array([1,2,3])
print(v)    
print(v.T)

[1 2 3]
[1 2 3]


In [37]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [38]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [39]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [40]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [41]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))

In [42]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [43]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
v = np.array([1, 2, 3])  
w = np.array([4, 5])    

In [45]:
print(np.reshape(v, (3, 1)) * w)


[[ 4  5]
 [ 8 10]
 [12 15]]


In [46]:
x = np.array([[1,2,3], [4,5,6]])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [47]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [48]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [49]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [2]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(np.arange(4))

[0 1 2 3]
